services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_logger_dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWD:-guest}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongo:7
    container_name: mongodb_logger_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  logger:
    build: .
    container_name: logger_service
    ports:
      - '8000:8000'
    environment:
      PYTHONUNBUFFERED: 1
      # Conexión a Mongo
      MONGODB_URL: mongodb://mongodb:27017
      MONGODB_DATABASE: log_aggregation
      # Conexión a RabbitMQ
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASSWD: ${RABBITMQ_PASSWD:-guest}
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data_dev: